all:
  hosts: {}
custom_configs:
  hosts:
    leaf1: {}
    leaf2: {}
    leaf3: {}
    spine1: {}
    spine2: {}
daemons:
  hosts: {}
eos:
  hosts:
    leaf1:
      ansible_host: 192.168.121.103
      id: 3
    leaf2:
      ansible_host: 192.168.121.104
      id: 4
    leaf3:
      ansible_host: 192.168.121.105
      id: 5
    spine1:
      ansible_host: 192.168.121.101
      id: 1
    spine2:
      ansible_host: 192.168.121.102
      id: 2
modules:
  hosts: {}
netlab_no_reload:
  hosts: {}
netlab_ready_ssh:
  hosts:
    leaf1: {}
    leaf2: {}
    leaf3: {}
    spine1: {}
    spine2: {}
unprovisioned:
  children: {}
  hosts: {}
