# Ansible inventory created from ['/home/alfredk/Projects/dc_design_labs/source/lab_04/netlab/topology.yml', '/home/alfredk/.netlab.yml', 'package:topology-defaults.yml']
#

all:
  hosts: {}
as65001:
  hosts:
    spine1: {}
as65002:
  hosts:
    spine2: {}
as65101:
  hosts:
    leaf1: {}
as65102:
  hosts:
    leaf2: {}
as65103:
  hosts:
    leaf3: {}
custom_configs:
  hosts:
    leaf1: {}
    leaf2: {}
    leaf3: {}
    spine1: {}
    spine2: {}
daemons:
  hosts: {}
eos:
  hosts:
    leaf1:
      ansible_host: 192.168.121.103
      id: 3
    leaf2:
      ansible_host: 192.168.121.104
      id: 4
    leaf3:
      ansible_host: 192.168.121.105
      id: 5
    spine1:
      ansible_host: 192.168.121.101
      id: 1
    spine2:
      ansible_host: 192.168.121.102
      id: 2
hosts:
  hosts:
    host1: {}
    host2: {}
    host3: {}
leaf:
  hosts:
    leaf1: {}
    leaf2: {}
    leaf3: {}
linux:
  hosts:
    host1:
      ansible_host: clab-netlab-host1
      id: 6
    host2:
      ansible_host: clab-netlab-host2
      id: 7
    host3:
      ansible_host: clab-netlab-host3
      id: 8
modules:
  hosts:
    host1: {}
    host2: {}
    host3: {}
    leaf1: {}
    leaf2: {}
    leaf3: {}
    spine1: {}
    spine2: {}
netlab_no_reload:
  hosts:
    host1: {}
    host2: {}
    host3: {}
netlab_ready_ssh:
  hosts:
    leaf1: {}
    leaf2: {}
    leaf3: {}
    spine1: {}
    spine2: {}
spine:
  hosts:
    spine1: {}
    spine2: {}
unprovisioned:
  hosts: {}
